### ISSUE TITLE
[Testing] Framework testing

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#189]
### Requirements
1. Cover main methods as well as significant boundary conditions.
2. Can be tested using unit tests or integration tests (transactional tests).

- [x] [raw_table.move](https://github.com/rooch-network/rooch/issues/190)
- [x] [table.move](https://github.com/rooch-network/rooch/issues/191)
- [x] [type_table.move](https://github.com/rooch-network/rooch/issues/192)
- [x] [object_storage.move](https://github.com/rooch-network/rooch/issues/193)
- [x] [account_storage.move](https://github.com/rooch-network/rooch/issues/194)
- [x] [account.move](https://github.com/rooch-network/rooch/issues/195)

**Comment by zlgu** [comment]
Hi, I want to do these issues.

**Comment by jolestar** [comment]
> Hi, I want to do these issues.

You can pick up one of them and leave a comment on the issue.

**Comment by zlgu** [comment]
OK
