### ISSUE TITLE
[Milestone] v0.8

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#2620]
### Proposal Details

- [x] DA Integration
- [x] [Babylon Integration](https://github.com/rooch-network/rooch/issues/2740)
- [ ] Gas reward to developer #2936 
- [x] Grow Bitcoin Campaign
- [x] Gas market
