### ISSUE TITLE
proposal: introduce atomic write and db repair tools for maintain storage(DA) consistency 

### ISSUE THREAD

**Issue by popcnt1** [rooch-network/rooch#2777]
#### We've found there is consistence issues between different storage node:

 - [x] inside sequenced tx: accumulator, tx_order, ledger_tx #2776 
 - [x] inside executed tx: startup_info, execution_info, states #2776 
 - [x] between sequenced and executed tx: rely on exection_info and tx_order:tx_hash mapping (could work well with #2776 )
- [ ] between executed tx and states chage set: rely on async notify, may lost signal after restart/collapse
- [ ] between indexer and executed tx: rely on async updates
- [ ] revert roochdb and indexer: rely on async updates(online); no mechanism in present(cmd #2769)
- [x] revert roochdb and DA: done(online, only ok tx will be put into DA buffer); need to update submitting states because tx_order may out of range after revert/rollback #2783 

#### Tools

- [x]  report inconsistent issues (mainly to search inconsistence between sequenced tx and executed tx): multi-get will be used for accelerate checking process, because we have to stop online server for  checking signle-process database #2849 
- [x]  try to repair db: collect all valid tx, rollback to consistent tx, and replay tx start from it #2849

**Comment by popcnt1** [comment]
except indexer issues, all fixed. Move to indexer only issue: #1409
