### ISSUE TITLE
proposal: da: approach to handle revert/rollback

### ISSUE THREAD

**Issue by popcnt1** [rooch-network/rooch#2783]
### Proposal Details

- [x] generate block range updates at server starting #2794 
- [x] update da store accroding to step1 #2794 
- [x] public last_submitted_block_number, accroding to this to fetch da batch #2817 
- [x]  RPC to access DA server status #2822

In one word, da will fix blocks info at server starting automatically

**Comment by popcnt1** [comment]
1,2: https://github.com/rooch-network/rooch/pull/2794
3: 2817

**Comment by popcnt1** [comment]
Done
