### ISSUE TITLE
Rooch v0.2 Milestone

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#411]
## MVP goal

The developer can use rooch as a backend service.

The developer can use js SDK and Crypto Wallet to interact with DApp.

Example project with Interface.

### Storage

@baichuan3 @jolestar 

- [x] Storage #9 #1 
- [x] #412 Transaction storage

### FrontEnd and DevTools

@wow-sven @yubing744 

- [x] JS SDK #306 #305 
- [x] #499
- [x] #416 

### VM and Verifier
@steelgeek091  @pause125 

- [x] #399
- [x] #248
- [x] #342
- [x] Integration test tool
- [x] Verifier relative issues  

### Framework

@jolestar 
 
- [x] #419 

### Examples

- [x] Counter with an interface
