### ISSUE TITLE
[Roadmap] Launch testing network

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#604]
- [x] Network name and domain TBD
- [x] Token Standard #627  
- [x] Timestamp #534 
- [x] Gas #421 Native Function Gas
- [x] Gas Provider or Faucet
- [x] CI and auto deploy
- [x] #515
